### PR TITLE
FIX Remove abandoned packages during the "update" process

### LINKED ISSUE #138: Clean up abandoned modules
http://addons.silverstripe.org/add-ons/simonwelsh/gridfieldrelationhandler
http://addons.silverstripe.org/add-ons/silverstripe/gridfield-relation-handler
http://addons.silverstripe.org/add-ons/simonwelsh

These modules have been marked as abandoned in Packagist (https://packagist.org/packages/simonwelsh/gridfieldrelationhandler) and should be either excluded from search results, or clearly marked so in our addons listings as well

### PR DESCRIPTION
**Pull request by robbieaverill**
During the update process we will delete `Addon` instances in the system that Packagist has identified as "abandoned". When the build task runs it won't encounter them again since they're gone.

Resolves #138

For reference - running locally identifies 48 abandoned packages.

### CODE REVIEW

File: mysite/code/services/AddonUpdater.php [hunk 1]
```diff
@@ -73,26 +74,34 @@ public function update($clear = false, $limitAddons = null) {
...
 
 			if (!$addon) {
 				$addon = new Addon();
 				$addon->Name = $name;
 				$addon->write();
+			} elseif ($isAbandoned) {
+				// Abandoned packages should be removed during updates
+				echo ' - Removing abandoned package: ' . $name, PHP_EOL;
+				$addon->delete();
+				continue;
```
Comment (robbieaverill) [inline mysite/code/services/AddonUpdater.php]: Edge case - package doesn't exist locally, first time it gets written then not deleted - would only be deleted the second time around.

File: mysite/code/services/AddonUpdater.php [hunk 2]
```diff
@@ -73,28 +74,42 @@ public function update($clear = false, $limitAddons = null) {
...
+		if ($this->usePackagistCache() && $packages = $cache->load('packagist')) {
 			$packages = unserialize($packages);
 		} else {
 			$packages = $this->packagist->getPackages();
 			$cache->save(serialize($packages), 'packagist');
 		}
 		$this->elastica->startBulkIndex();
 
-		foreach ($packages as $package) {
+		foreach ($packages as $package) { /** @var Packagist\Api\Result\Package $package */
```
Comment (dhensby) [inline mysite/code/services/AddonUpdater.php]: Can you place the phpdoc on the line above the delcarations, please

**Comment by dhensby** [comment]
seems legit to me. just a small note on placing of the inline phpdoc line

**Comment by robbieaverill** [comment]
@dhensby Updated, thanks

**Comment by robbieaverill** [comment]
@dhensby you happy with this now?

**Comment by dhensby** [comment]
I might say that abandoned packages maybe should still be indexed but hidden by default? Abandoned packages can still provide value, surely?

**Comment by robbieaverill** [comment]
@dhensby haha - [see comment](https://github.com/silverstripe/addons.silverstripe.org/issues/138#issuecomment-266714744) ;)

There's two schools of thought:

1) Abandoned packages should/can not be used, especially when SilverStripe 4 becomes "the" version, most of the currently abandoned packages will be entirely obsolete. People can still find them on GitHub or Packagist if they wanted to, for example if someone is trying to find a package they're using but it doesn't show up on addons any more.

2) They're still SilverStripe modules, and the abandonment instructions they probably contain could be useful for people to find replacement modules with.

I guess \#2 above caters for developers (and non-developers) that aren't aware of or don't think of using Packagist for this kind of thing, whereas \#1 possibly applies to everyone in terms of the goal of addons, which is presumably to expose users to the different types of modules they *can* use for their SilverStripe project.

I'm happy to make the change to put them back in, as long as we can have a design concept of some sort for an obvious abandonment message on the listing page. This ties into a raft of other improvement ideas that I know have been in the works for some time now though.

**Comment by dhensby** [comment]
I think there's a distinction between abandoned packages that are no longer maintained but the source code is still available and packages where the source code is gone. The former can be useful, the latter not so.

What is addons using to determine if a module is "abandoned"? Because technically all the silverstripe-archive modules are abandoned, but would be useful to list on the addons site (with the correct filter activated).

While I agree that once we move to 4.x the abandoned 3.x modules become increasingly unhelpful, however 4.x modules will slowly become abandoned too, so it's not an issue that goes away once 4.x is widely adopted.

I wouldn't prioritise it, but I think having it as some kind of open feature request to allow the inclusion of abandoned packages in search results could be helpful.

**Comment by robbieaverill** [comment]
>I think there's a distinction between abandoned packages that are no longer maintained but the source code is still available and packages where the source code is gone. The former can be useful, the latter not so.

Yeah - for the record, I believe that non-existent modules were already deleted before this change was merged.

>What is addons using to determine if a module is "abandoned"?

The Packagist API has a field for whether a module is "abandoned".

>Because technically all the silverstripe-archive modules are abandoned, but would be useful to list on the addons site (with the correct filter activated).

True.

---

Perhaps you're right - and we should revert this commit and label them somehow on the frontend as abandoned instead...
