### PR TITLE
API Add GitHubMarkdownService and update composer dependencies

### LINKED ISSUE #61: Render github Markdown through their parser
We use `MarkdownParser`, not even `MarkdownExtraParser`. Most obviously breaks on unparsed tables, but also things like fenced code blocks with triple backticks. 

Broken example: http://addons.silverstripe.org/add-ons/heyday/silverstripe-composeparser
image

Use the Github API to render Markdown if hosted on Github instead (http://developer.github.com/v3/markdown/). Also has the advantage that relative links resolve correctly.

BTW, we currently use the https://github.com/dflydev/dflydev-markdown lib.

### LINKED ISSUE #90: Render markdown using GitHub Flavour
Table doesn't render, as seen here:
http://addons.silverstripe.org/add-ons/burnbright/silverstripe-shop

### LINKED ISSUE #115: dflydev/markdown deprecated and needs replacing
Need to replace deprecated dflydev/markdown with michelf/php-markdown (see composer.json).

See silverstripe/addons.silverstripe.org/pull/110.

### LINKED ISSUE #141: Replace guzzle/guzzle with guzzlehttp/guzzle
As per composer installation's suggestion:

```
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
```

The package has just been renamed, so is just an update to `composer.json`.

### PR DESCRIPTION
**Pull request by robbieaverill**
* Replace dflydev/markdown with GitHub markdown parsing via API
* Tidy up readme formatting
* Fix some composer validation failures in composer.json
* Change editor config to be closer to PSR-2, add doc blocks to BuildTasks

This resolves #141, resolves #61, resolves #90 and resolves #115.

# To-do

- [x] Use GitHub API to render markdown instead of erusev/parsedown
- [x] Update guzzlehttp/guzzle for general use
- [x] Ensure legacy guzzle/guzzle still works with Packagist API
- [x] Test update/build addon tasks and frontend

### CODE REVIEW

**Comment by robbieaverill** [comment]
- [ ] Use GitHub API to render markdown instead of erusev/parsedown
- [ ] Update guzzlehttp/guzzle for general use
- [ ] Ensure legacy guzzle/guzzle still works with Packagist API

**Comment by robbieaverill** [comment]
- [ ] I'll do a bit of build/update testing for the addons before this gets reviewed or merged.

File: mysite/code/tasks/DeleteRedundantAddonsTask.php [hunk 1]
```diff
@@ -1,37 +1,53 @@
...
+
+        $addons = Addon::get()->filter('LastUpdated:LessThan', $dateOneWeekAgo);
+
+        foreach ($addons as $addon) { /** @var Addon $addon */
+            try {
+                $addon->Keywords()->removeAll();
+                $addon->Screenshots()->removeAll();
+                $addon->CompatibleVersions()->removeAll();
+
+                foreach ($addon->Versions() as $version) { /** @var AddonVersion $version */
```
Comment (dhensby) [inline mysite/code/tasks/DeleteRedundantAddonsTask.php]: Inline phpDoc should be on line above

File: mysite/code/tasks/DeleteRedundantAddonsTask.php [hunk 2]
```diff
@@ -1,37 +1,53 @@
...
+     */
+    public function run($request)
+    {
+        $dateOneWeekAgo  = date('Y-m-d', strtotime('-1 week'));
+
+        $addons = Addon::get()->filter('LastUpdated:LessThan', $dateOneWeekAgo);
+
+        foreach ($addons as $addon) { /** @var Addon $addon */
+            try {
+                $addon->Keywords()->removeAll();
```
Comment (dhensby) [inline mysite/code/tasks/DeleteRedundantAddonsTask.php]: Shouldn't all the relation unmatching be done `onBeforeDelete` on `Addon`?

File: mysite/code/tasks/BuildAddonsTask.php [hunk 3]
```diff
@@ -1,42 +1,66 @@
...
+        if ($request->getVar('addons')) {
+            $addons = $addons->filter('Name', explode(',', $request->getVar('addons')));
+        }
 
-	public function run($request) {
-		$addons = Addon::get();
-		if($request->getVar('addons')) {
-			$addons = $addons->filter('Name', explode(',', $request->getVar('addons')));
-		}
+        foreach($addons as $addon) { /** @var Addon $addon */
```
Comment (dhensby) [inline mysite/code/tasks/BuildAddonsTask.php]: Inline type hint to go on line above, please

File: mysite/code/services/AddonBuilder.php [hunk 4]
```diff
@@ -91,8 +90,8 @@ private function buildReadme(Addon $addon, $path) {
 					return;
 				}
 
-				$parser = new MarkdownParser();
-				$readme = $parser->transformMarkdown(file_get_contents($path));
+				$parser = GitHubMarkdownService::create();
+				$readme = $parser->toHtml(file_get_contents($path));
```
Comment (dhensby) [inline mysite/code/services/AddonBuilder.php]: if the parser fails (API timeout, rate limit, GH down, whatever) then we're going to override all the readmes with empty string.

Can we attempt to catch that and no override the readme?

File: mysite/code/tasks/DeleteRedundantAddonsTask.php (hunk 2 above)
Comment (robbieaverill) [inline mysite/code/tasks/DeleteRedundantAddonsTask.php]: I hadn't actually looked much at these parts, it's mostly showing these lines up because of indentation changes

**Comment by robbieaverill** [comment]
Hey @dhensby - I've moved the PHPDoc lines and added a handler for where the markdown parser fails or returns nothing.

As for the context - there isn't a way to pass a repository context to the GitHub markdown API endpoint. The relative URLs and paths are handled in #143

**Comment by dhensby** [comment]
> As for the context - there isn't a way to pass a repository context to the GitHub markdown API endpoint.

There is: https://developer.github.com/v3/markdown/#parameters

**Comment by robbieaverill** [comment]
Heh true. So this would give us auto linked issues, pull requests and user mentions. I notice that the docs seem to imply that GitHub themselves don't use context aware parsing for readme files.

Should be a quick change to make anyway though, so I'll throw it in shortly.

**Comment by dhensby** [comment]
> I notice that the docs seem to imply that GitHub themselves don't use context aware parsing for readme files.

Yes, though this surely isn't right as I've seen readmes reference issues by number before... unless they'd just hard coded that markdown...

Regardless - using an external API and the risks that brings should provide some tangible benefit over using a library to out-weigh the risks of it being unreliable (ie: sometimes down)

**Comment by robbieaverill** [comment]
@dhensby: cool, changes pushed.

For the sake brevity, here are my thoughts overall for using the GitHub API

## Benefits

* Consistency between a repository's readme in GitHub and addons.ss (primary reason for doing this)
* Ability to render GitHub flavoured markdown
* Fix relative links and images (covered in #143) - not directly a cause of having this implemented though
* Don't rely on third party libraries like michelf/php-markdown or erusev/parsedown which erode and get abandoned over time (php-markdown is a good example - it continues to become less and less friendly with modern web apps)
* GitHub can control how markdown is rendered. If they decide to parse relative links to full links in future, we don't need to change anything - yay!

## Drawbacks

* API call while building every module: this is offset by the fact that we build behind the scenes. I wouldn't advocate implementing this if we were rendering on a page load, say
* Riskier: networks can die
* Slower: cross-network calls are slower than loading an installed library

File: mysite/code/services/GitHubMarkdownService.php [hunk 5]
```diff
@@ -107,4 +134,22 @@ public function getHeaders()
...
+     * @param  string $markdown
+     * @return string           JSON
+     */
+    public function getPayload($markdown)
+    {
+        return Convert::raw2json(
+            array(
+                'text'    => $markdown,
+                'mode'    => 'gfm',
+                'context' => $this->getContext()
```
Comment (dhensby) [inline mysite/code/services/GitHubMarkdownService.php]: Does this work if there's no context?

File: mysite/code/services/AddonBuilder.php [hunk 6]
```diff
@@ -91,7 +91,9 @@ private function buildReadme(Addon $addon, $path) {
                 }
 
                 $parser = GitHubMarkdownService::create();
+                $parser->setContext($addon->Name);
```
Comment (dhensby) [inline mysite/code/services/AddonBuilder.php]: I think we need to be a bit more clever here. The context is the the `[user]/[repo]` string not just the name of the add on (which could be different) - for example `silverstripe/fulltextsearch` is actually `silverstripe/silverstripe-fulltextsearch` on github.

I think we should check the repo URL is on GH and also determine the repo slug.

If it's not a GH repo  then don't set the context. If the context isn't set the MarkdownService should just use the RAW endpoint (or not set the context if that's the same result)

**Comment by robbieaverill** [comment]
I'll be coming back to this

**Comment by robbieaverill** [comment]
@dhensby - sorry, took me a while to get back to this but I've updated as per your comments:

* Check for a GitHub context in the repo URL
* Get the "context" from the URL, not the composer package name
* Parse as "raw" mode if not GitHub context, and "gfm" mode if GitHub context
* Added our first unit test! 🎉

**Comment by dhensby** [comment]
Fantastic

**Comment by dhensby** [comment]
I guess my final question is... Have you tested this locally to ensure it works on our dataset?

Are there API restrictions, will we need an API ket?

**Comment by robbieaverill** [comment]
Yeah it will probably need a key to prevent rate limiting. I will add this
into a separate PR if that suits you

**Comment by dhensby** [comment]
Better use an environment var and keep it out of code. But it will need config somehow

**Comment by robbieaverill** [comment]
Yeah totally. I think it's a couple of headers for the guzzle req
