### PR TITLE
API Remove HelpfulRobot tasks and implementation in favour of silverstripe/moduleratings

### LINKED ISSUE #172: Helpfulrobot broken
It looks like the upstream service supplying the helpfulrobot data, is broken. As I understand it, http://helpfulrobot.io/silverstripe/framework, for example, should return JSON, but isn't.

The current addons.silverstripe.org site has a lot of historic data from helpful robot still stored, but new modules don't have anything.

Notably, I've been working on a migration to a new server and that would require re-fetching all the helpful robot data, but it won't be able to do this.

### PR DESCRIPTION
**Pull request by robbieaverill**
This switches helpful robot for [module ratings](https://github.com/creative-commoners/moduleratings).

Todo:

- [x] Run a full test (including queuedjobs implementation) on SSP stack (in progress)
- [x] Confirm supported module standard criteria is still valid
- [x] Confirm [check points allocation](https://github.com/creative-commoners/moduleratings/blob/0.3.0/config.yml) is OK 
- [x] Submit moduleratings and moduleratings-plugin to packagist/move to SS organisation/remove VCS repos from composer.json

Example check table:

image

Resolves #172

### CODE REVIEW

File: mysite/code/services/AddonBuilder.php [hunk 1]
```diff
@@ -306,4 +311,40 @@ private function buildScreenshots(Addon $addon, PackageInterface $package, $path
...
+
+    /**
+     * Use the Rating check runner to generate an automated rating for this module
+     *
+     * @param Addon $addon
+     * @param string $modulePath
+     */
+    protected function rateModule(Addon $addon, $modulePath)
+    {
+        $suite = new CheckSuite();
```
Comment (sminnee) [inline mysite/code/services/AddonBuilder.php]: If this were an injected service, there would be more scope for configuring the checks applied in YML config.

File: themes/addons/templates/Layout/Addon.ss [hunk 2]
```diff
@@ -1,254 +1,190 @@
...
+				<p>N/A <small>No data avaliable</small></p>
+				<% end_if %>
+			</div>
+			<p>Module rating system helping users find modules that are well supported. For more on how the rating system works visit <a href="http://www.silverstripe.org/software/addons/supported-modules-definition/">Module standards</a></p>
+			<p><small>Score not correct? <a href="mailto:community@silverstripe.com">Let us know there is a problem</a></small></p>
+		</div>
+
+		<% if $RatingData %>
+		<div class="span3 offset1">
+            <% include ModuleRatingEntry Metric=$RatingData.has_readme, Description="Readme" %>
```
Comment (sminnee) [inline themes/addons/templates/Layout/Addon.ss]: This really seems like it wants to be a <% loop %>

**Comment by sminnee** [comment]
Fatal error if Rating Data is null. This is a merge blocker

```
[User Error] Uncaught InvalidArgumentException: Parameter to ArrayData constructor needs to be an object or associative array
GET /add-ons/silverstripe/framework?isDev=1&isDevtoken=c491f577f4f780eb2e0c57727a17043f
Line 36 in /var/www/mysite/releases/0970304a51b63d4cb93ed1cf11d498d65f13ba77/framework/view/ArrayData.php

Source
27 	public function __construct($value) {
28 		if (is_object($value)) {
29 			$this->array = get_object_vars($value);
30 		} elseif (ArrayLib::is_associative($value)) {
31 			$this->array = $value;
32 		} elseif (is_array($value) && count($value) === 0) {
33 			$this->array = array();
34 		} else {
35 			$message = 'Parameter to ArrayData constructor needs to be an object or associative array';
36 			throw new InvalidArgumentException($message);
37 		}
38 		parent::__construct();
39 	}
40 
41 	/**
42 	 * Get the source array
Trace
ArrayData->__construct() 
ReflectionClass->newInstanceArgs(Array) 
InjectionCreator.php:17
InjectionCreator->create(ArrayData,Array) 
Injector.php:555
Injector->instantiate(Array) 
Injector.php:864
Injector->get(ArrayData,,Array) 
Injector.php:902
Injector->createWithArgs(ArrayData,Array) 
Object.php:142
Object::create() 
Addon.php:183
Addon->RatingData() 
ViewableData.php:466
ViewableData->obj(RatingData,,,1,RatingData) 
ViewableData.php:504
ViewableData->cachedCall(RatingData,) 
ViewableData.php:517
ViewableData->hasValue(RatingData,,1) 
DataObject.php:4067
DataObject->hasValue(RatingData,,1) 
SSViewer.php:187
SSViewer_Scope->__call(hasValue,Array) 
SSViewer.php:650
SSViewer_DataPresenter->__call(hasValue,Array) 
.cache.themes.addons.templates.Layout.Addon.ss:297
include(/tmp/silverstripe-cache-php7.1.12-1+0-20171129100725.11+jessie-1.gbp8ded15-var-www-mysite-releases-0970304a51b63d4cb93ed1cf11d498d65f13ba77/www-data/.cache.themes.addons.templates.Layout.Addon.ss) 
SSViewer.php:1164
SSViewer->includeGeneratedTemplate(/tmp/silverstripe-cache-php7.1.12-1+0-20171129100725.11+jessie-1.gbp8ded15-var-www-mysite-releases-0970304a51b63d4cb93ed1cf11d498d65f13ba77/www-data/.cache.themes.addons.templates.Layout.Addon.ss,AddonController,,Array,) 
SSViewer.php:1226
SSViewer->process(AddonController,) 
SSViewer.php:1222
SSViewer->process(AddonController,) 
ViewableData.php:405
ViewableData->renderWith(SSViewer) 
AddonController.php:25
AddonController->index(SS_HTTPRequest) 
RequestHandler.php:288
RequestHandler->handleAction(SS_HTTPRequest,index) 
Controller.php:202
Controller->handleAction(SS_HTTPRequest,index) 
RequestHandler.php:200
RequestHandler->handleRequest(SS_HTTPRequest,DataModel) 
Controller.php:158
Controller->handleRequest(SS_HTTPRequest,DataModel) 
RequestHandler.php:222
RequestHandler->handleRequest(SS_HTTPRequest,DataModel) 
Controller.php:158
Controller->handleRequest(SS_HTTPRequest,DataModel) 
Director.php:385
Director::handleRequest(SS_HTTPRequest,Session,DataModel) 
Director.php:149
Director::direct(/add-ons/silverstripe/framework,DataModel) 
main.php:191
```

Can currently witness on https://ssaddons-uat.sites.silverstripe.com/add-ons/silverstripe/framework?isDev=1 but that will go away once it's been processed by the queued jobs.

**Comment by sminnee** [comment]
OK I think I fixed that.

File: mysite/code/services/AddonBuilder.php (hunk 1 above)
Comment (robbieaverill) [reply mysite/code/services/AddonBuilder.php]: yep makes sense

File: themes/addons/templates/Layout/Addon.ss (hunk 2 above)
Comment (robbieaverill) [reply themes/addons/templates/Layout/Addon.ss]: Yeah. I'd love it to come from the config.yml in the module, but not sure what the best way to do it would be. I've been removing the check description during import since its the same for every module and would just waste DB space. For now I'll put these into a controller method and loop it instead

**Comment by robbieaverill** [comment]
Updated with both your comments @sminnee - re-deploying to UAT now

**Comment by sminnee** [comment]
There's a bug with ratings that I think has been introduced by CheckSuite's conversion to a service - the points get very high.

**Comment by sminnee** [comment]
Related: https://github.com/creative-commoners/moduleratings/pull/7

**Comment by robbieaverill** [comment]
I've added a configurable page size dropdown to the jobs list (15 wasn't enough!).

It looks like elasticsearch isn't connecting though

**Comment by robbieaverill** [comment]
We're still getting shared instance data from the check suite - I'm going to revert the injection change for it and put it back to a new instance each time

**Comment by sminnee** [comment]
> We're still getting shared instance data from the check suite - I'm going to revert the injection change for it and put it back to a new instance each time

Fair call, it was causing a few issues eh

**Comment by robbieaverill** [comment]
So a quick summary of where we're at so far:

* Deployed to a prod SSP stack
* Builds are running correctly
* Ratings are running correctly
* Some old data may still be present from when a module was incorrectly given a 100/100 (or more) rating, then hasn't been updated since, I haven't noticed obvious examples of this recently though
* Elasticsearch is not running (blocker)

**Comment by robbieaverill** [comment]
Found a bug where the coding standards check was analysing css and js files and incorrectly failing the check. Updated.

**Comment by robbieaverill** [comment]
@sminnee @chillu @be2n I'd like to get the DNS switched over to the platform stack running this new version on Monday. Do you have a problem with me shifting the module ratings and module ratings composer plugins to the SilverStripe GitHub account first, or silverstripeltd?

**Comment by chillu** [comment]
I'm fine with module ratings on `github.com/silverstripe`, it's the same level of support/maintenance as addons - and that's already on that account.

**Comment by robbieaverill** [comment]
Ok great, packages moved over. We're good to go with this then!

**Comment by robbieaverill** [comment]
Wrong button =(

**Comment by robbieaverill** [comment]
I've pushed a couple of pull requests to silverstripe/moduleratings to update some of the stuff I didn't have time for last weekend. If someone could merge them then we can update this repo and re-deploy to SSP!
